# Generated by Django 3.2.16 on 2024-11-30 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Слаг')),
                ('output_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spendings', to='spending.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Трата',
                'verbose_name_plural': 'Траты',
            },
        ),
    ]
