# Generated by Django 3.2.16 on 2024-11-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=9)),
                ('card', models.DecimalField(decimal_places=2, max_digits=9)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
